"""add log deletion timeout to camera

Revision ID: 1c67d4d293ef
Revises: 076b155027ad
Create Date: 2026-01-30 10:29:00.590379+00:00

"""

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '1c67d4d293ef'
down_revision = '076b155027ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('camera_latency', 'rtt_avg',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Average Round Trip Time in ms',
               existing_nullable=True)
    op.alter_column('camera_latency', 'rtt_min',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Minimum Round Trip Time in ms',
               existing_nullable=True)
    op.alter_column('camera_latency', 'rtt_max',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Maximum Round Trip Time in ms',
               existing_nullable=True)
    op.alter_column('camera_latency', 'packet_loss_percent',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Packet loss percentage',
               existing_nullable=True)
    op.alter_column('camera_latency', 'packets_sent',
               existing_type=sa.INTEGER(),
               comment='Number of packets sent',
               existing_nullable=True)
    op.alter_column('camera_latency', 'packets_received',
               existing_type=sa.INTEGER(),
               comment='Number of packets received',
               existing_nullable=True)
    op.alter_column('camera_latency', 'is_reachable',
               existing_type=sa.BOOLEAN(),
               comment='Whether camera is reachable',
               existing_nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('camera_latency', 'check_type',
               existing_type=sa.VARCHAR(length=20),
               comment='Type of connectivity check (PING, TCP, etc.)',
               existing_nullable=True,
               existing_server_default=sa.text("'PING'::character varying"))
    op.alter_column('camera_latency', 'error_message',
               existing_type=sa.TEXT(),
               comment='Error message if check failed',
               existing_nullable=True)
    op.drop_index('ix_camera_latency_camera_timestamp', table_name='camera_latency')
    op.add_column('cameras', sa.Column('log_delete_timeout_seconds', sa.Integer(), nullable=True, comment='How long to keep health logs for this camera (seconds)'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cameras', 'log_delete_timeout_seconds')
    op.create_index('ix_camera_latency_camera_timestamp', 'camera_latency', ['camera_id', 'timestamp'], unique=False)
    op.alter_column('camera_latency', 'error_message',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Error message if check failed',
               existing_nullable=True)
    op.alter_column('camera_latency', 'check_type',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Type of connectivity check (PING, TCP, etc.)',
               existing_nullable=True,
               existing_server_default=sa.text("'PING'::character varying"))
    op.alter_column('camera_latency', 'is_reachable',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Whether camera is reachable',
               existing_nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('camera_latency', 'packets_received',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Number of packets received',
               existing_nullable=True)
    op.alter_column('camera_latency', 'packets_sent',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Number of packets sent',
               existing_nullable=True)
    op.alter_column('camera_latency', 'packet_loss_percent',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Packet loss percentage',
               existing_nullable=True)
    op.alter_column('camera_latency', 'rtt_max',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Maximum Round Trip Time in ms',
               existing_nullable=True)
    op.alter_column('camera_latency', 'rtt_min',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Minimum Round Trip Time in ms',
               existing_nullable=True)
    op.alter_column('camera_latency', 'rtt_avg',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Average Round Trip Time in ms',
               existing_nullable=True)
    # ### end Alembic commands ###
