"""rename_metadata_to_meta_data

Revision ID: 2e2fd96653a5
Revises: 64c7b9b023ee
Create Date: 2026-01-23 08:41:56.368503+00:00

"""

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '2e2fd96653a5'
down_revision = '64c7b9b023ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
