"""initial vigilx schema

Revision ID: 64c7b9b023ee
Revises: 
Create Date: 2026-01-23 07:06:48.906627+00:00

"""

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '64c7b9b023ee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cameras',
    sa.Column('camera_id', sa.String(length=64), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('rtsp_url', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('interval_ip', sa.Integer(), nullable=True),
    sa.Column('interval_port', sa.Integer(), nullable=True),
    sa.Column('interval_vision', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('camera_id')
    )
    op.create_table('health_logs',
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('camera_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('event_description', sa.Text(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('last_checked', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.camera_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_health_logs_timestamp'), 'health_logs', ['timestamp'], unique=False)
    op.create_table('alerts',
    sa.Column('alert_id', sa.String(length=36), nullable=False),
    sa.Column('camera_id', sa.String(length=64), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('alert_description', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.camera_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['health_logs.event_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('alert_id')
    )
    op.create_index(op.f('ix_alerts_timestamp'), 'alerts', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alerts_timestamp'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_health_logs_timestamp'), table_name='health_logs')
    op.drop_table('health_logs')
    op.drop_table('cameras')
    # ### end Alembic commands ###
